# Generated by Django 5.1.5 on 2025-06-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('headquarters', models.CharField(max_length=255)),
                ('founded', models.IntegerField()),
                ('website', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
